2014/08/21 15:17:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "graphs" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('graphs')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=graphs
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 15:18:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "graphs" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('graphs')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=graphs
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 15:19:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "graphs" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('graphs')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=graphs
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 17:13:07 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'servicios.usuario' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `usuario`.
in C:\xampp\htdocs\servicios\index.php (13)
2014/08/21 19:08:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "home2" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('home2')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=home2
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 19:08:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "home2" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('home2')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=home2
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 19:09:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "home2" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('home2')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=home2
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 19:10:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "home2" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('home2')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=home2
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 19:10:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "home2" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('home2')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=home2
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 19:10:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "home2" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('home2')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/servicios/index.php?r=site/page&view=home2
HTTP_REFERER=http://localhost/servicios/index.php?r=site/index
---
2014/08/21 19:16:49 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/servicios/index.php?r=usuarios/admin
HTTP_REFERER=http://localhost/servicios/index.php?r=site/login
---
2014/08/21 19:29:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "estudiantes".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('estudiantes')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/servicios/index.php?r=estudiantes
---
2014/08/21 19:49:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "tutores/admin".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tutores/admin')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/servicios/index.php?r=tutores/admin&view=about
HTTP_REFERER=http://localhost/servicios/index.php?r=estudiante/admin&view=about
---
2014/08/21 19:50:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "tutores/admin".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tutores/admin')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/servicios/index.php?r=tutores/admin&view=about
HTTP_REFERER=http://localhost/servicios/index.php?r=estudiante/admin&view=about
---
2014/08/21 19:50:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "tutore/admin".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tutore/admin')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/servicios/index.php?r=tutore/admin&view=about
HTTP_REFERER=http://localhost/servicios/index.php?r=tutores/admin&view=about
---
2014/08/21 19:51:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "tutore/admin".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tutore/admin')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/servicios/index.php?r=tutore/admin&view=about
HTTP_REFERER=http://localhost/servicios/index.php?r=tutores/admin&view=about
---
2014/08/22 02:22:28 [error] [php] Undefined index: Password (C:\xampp\htdocs\servicios\protected\controllers\UsuariosController.php:73)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UsuariosController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UsuariosController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): UsuariosController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UsuariosController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\servicios\index.php(13): CWebApplication->run()
REQUEST_URI=/servicios/index.php?r=usuarios/create
in C:\xampp\htdocs\servicios\protected\controllers\UsuariosController.php (73)
in C:\xampp\htdocs\servicios\index.php (13)
2014/08/22 02:24:03 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.Password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('Password', 'd033e22ae348aeb...')
#1 C:\xampp\htdocs\servicios\protected\controllers\UsuariosController.php(73): CActiveRecord->__set('Password', 'd033e22ae348aeb...')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsuariosController->actionCreate()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/create')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/servicios/index.php?r=usuarios/create
HTTP_REFERER=http://localhost/servicios/index.php?r=usuarios/create
---
2014/08/22 02:29:48 [error] [php] Undefined index: password (C:\xampp\htdocs\servicios\protected\controllers\UsuariosController.php:74)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UsuariosController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UsuariosController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): UsuariosController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UsuariosController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\servicios\index.php(13): CWebApplication->run()
REQUEST_URI=/servicios/index.php?r=usuarios/create
in C:\xampp\htdocs\servicios\protected\controllers\UsuariosController.php (74)
in C:\xampp\htdocs\servicios\index.php (13)
2014/08/22 02:31:26 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.idUs" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('idUs')
#1 C:\xampp\htdocs\servicios\protected\controllers\UsuariosController.php(76): CActiveRecord->__get('idUs')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UsuariosController->actionCreate()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/create')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/servicios/index.php?r=usuarios/create
HTTP_REFERER=http://localhost/servicios/index.php?r=usuarios/create
---
2014/08/22 02:36:00 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.Password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('Password')
#1 C:\xampp\htdocs\servicios\protected\components\UserIdentity.php(26): CActiveRecord->__get('Password')
#2 C:\xampp\htdocs\servicios\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\servicios\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\servicios\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/servicios/index.php?r=site/login
HTTP_REFERER=http://localhost/servicios/index.php?r=site/login
---
